import type { Metadata } from "next";
import { Libre_Baskerville, IBM_Plex_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";

const fontHeader = Libre_Baskerville({
  variable: "--font-header",
  subsets: ["latin"],
});

const fontMain = IBM_Plex_Sans({
  variable: "--font-main",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontHeader.variable} ${fontMain.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
